### ISSUE TITLE
Log message format changed in MongoDB 4.4

### ISSUE THREAD

**Issue by ajvondrak** [honeycombio/mongodbtools#10]
Starting in version 4.4, MongoDB changed its log messages to a [structured JSON format](https://docs.mongodb.com/manual/reference/log-messages/#json-log-output-format), but the parser only recognizes the old formats (e.g., [the format circa 4.2](https://docs.mongodb.com/v4.2/reference/log-messages/), though there appears to be [some logic](https://github.com/honeycombio/mongodbtools/blob/0f4cb16d2dd202868b79df184f1f440d776444eb/logparser/internal/logparser/log_line.go#L72-L72) for handling pre-3.0 versions as well).

A possible workaround in Honeytail would be to use the JSON parser instead. However, the timestamp format is going to be problematic because MongoDB's JSON structure isn't flat:

```json
{
  "t": {
    "$date": "2020-05-01T15:16:17.180+00:00"
  },
  "s": "I",
  "c": "NETWORK",
  "id": 12345,
  "ctx": "listener",
  "msg": "Listening on",
  "attr": {
    "address": "127.0.0.1"
  }
}
```

You couldn't just specify `--json.timefield="t"` because the value is further nested under the `"$date"` key. It could be possible to perform some acrobatics to rewrite the JSON before piping it into Honeytail (for example, using `jq`), but nothing out of the box.

I think the MongoDB parser could assume the log format is version 4.4+ if the first character is a `{`. Then it's a matter of consuming the JSON and plucking out the right fields.

**Comment by MikeGoldsmith** [comment]
Thanks for creating the issue @ajvondrak.

We'll add it to our backlog to decide on next steps.

PS we (@honeycombio/telemetry-team) are waiting on getting write access to this repo, so we can manage it going forward.

**Comment by vreynolds** [comment]
- #20
